# Generated by Django 4.0 on 2021-12-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=255, verbose_name='Product vendor code')),
                ('image_360_path', models.FileField(upload_to='', verbose_name='Image 360 path')),
            ],
        ),
    ]
