# Generated by Django 4.0 on 2021-12-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0004_unpack3dmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
