# Generated by Django 4.0 on 2021-12-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0006_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
