# Generated by Django 4.0 on 2021-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0011_alter_model3darchive_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3darchive',
            name='size',
            field=models.CharField(default=1000, editable=False, max_length=255),
        ),
    ]
