# Generated by Django 4.0 on 2021-12-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0015_delete_unpack3dmodel_alter_model3darchive_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image360',
            name='image_360_path',
            field=models.FileField(max_length=255, null=True, upload_to='3d_models/imported/%Y/%m/%d/', verbose_name='Image 360 path'),
        ),
        migrations.AlterField(
            model_name='image360',
            name='vendor_code',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name='Product vendor code'),
        ),
    ]
