# Generated by Django 4.0 on 2021-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0016_alter_image360_image_360_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image360',
            name='image_360_path',
            field=models.FileField(max_length=255, null=True, upload_to='3d_models/models/%Y/%m/%d/', verbose_name='Image 360 path'),
        ),
    ]
