# Generated by Django 4.0 on 2021-12-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0017_alter_image360_image_360_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image360',
            old_name='image_360_path',
            new_name='iframe',
        ),
    ]
