# Generated by Django 4.0 on 2021-12-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0019_alter_image360_options_alter_image360_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255, unique=True, verbose_name='Web site')),
                ('api_key', models.CharField(max_length=255, verbose_name='Api key')),
            ],
            options={
                'verbose_name': 'Web site',
                'verbose_name_plural': 'Web sites',
            },
        ),
    ]
