# Generated by Django 4.0 on 2021-12-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0020_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Api key'),
        ),
    ]
