# Generated by Django 4.0 on 2021-12-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0022_alter_website_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website',
            field=models.CharField(help_text='enter website domain you want to provide images 360 access for', max_length=255, unique=True, verbose_name='Web site'),
        ),
    ]
