# Generated by Django 4.0 on 2021-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0025_alter_website_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, help_text='Enter api key for images 360 access', max_length=255, verbose_name='Api key'),
        ),
    ]
