# Generated by Django 4.0 on 2021-12-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0029_image360_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model3dArchive',
            new_name='Image360Archive',
        ),
    ]
