# Generated by Django 4.0 on 2021-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0030_rename_model3darchive_image360archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, help_text='Enter API key for image 360 access or live it empty in order the system generated it automatically', max_length=255, unique=True, verbose_name='Api key'),
        ),
    ]
