# Generated by Django 4.0 on 2021-12-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0032_updateimages360url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateImages360Url',
            new_name='RemoteUpdateImages360Url',
        ),
    ]
