# Generated by Django 4.0 on 2021-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0033_rename_updateimages360url_remoteupdateimages360url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteupdateimages360url',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
