# Generated by Django 4.0 on 2021-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0034_alter_remoteupdateimages360url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image360archive',
            name='vendor_code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Vendor code'),
        ),
    ]
