# Generated by Django 4.0 on 2021-12-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image360upload', '0035_image360archive_vendor_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remoteupdateimages360url',
            options={'verbose_name': 'Images 360 upload on remote websites'},
        ),
        migrations.AlterField(
            model_name='remoteupdateimages360url',
            name='url',
            field=models.CharField(blank=True, help_text='Specify remote resource url by which images 360 import is performed', max_length=255, null=True),
        ),
    ]
